##############################################################################
# Project: 	SeegridS2SevconCAN
# Module: 	sevcon_mover.py
# Purpose: 	Write values to a file to make the sevcon motor move to an angle.
# Language:	Python 3.5
# Date:		16-Sep-2013.
# Ver.:		16-Sep-2013.
# Copyright:	2013 - 2014 - S. Selvam Raju @SEEGRID corp.       <sraju@seegrid.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# Important:	WHEN EDITING THIS FILE, USE TABS TO INDENT - NOT SPACES!
##############################################################################

# Name of this program.
_SOFTNAME = 'Sevcon_Mover'

# Version of this server.
_VERSION = '16-Sep-2013'

_HelpStr = """
%s, %s
This module writes a text file in a PCan driver accessible format to send CAN messages to the SEVCON motor to turn to particular angles. The module currently accepts the HEX bytes for the move command and will be modified (in near future) to take angles in degrees as inputs. This text will be modified after each revision of this program.

""" % (_SOFTNAME, _VERSION)

############################################################

###Imports###
import os
import time


###Get User input###
print "The sevcon accepts data from 0000 to FFFF in Hex format to mover from 0 to 360 degrees.\nPlease enter the Lower Byte and the Upper byte to be able to move the motor"


while True:
	lowerByte = raw_input("\nEnter Lower Byte: ")
	upperByte = raw_input("\nEnter Upper Byte: ")
	print "\nThe entered values are: LB: " + lowerByte + "  UB: " + upperByte

	###Write to file###
	file = open("move_sevcon.txt","w")
	file.write("#CAN messages for Sevcon position control\n")
	file.write("#This file is autogenerated by sevcon_mover.py\n")
	###Writing to addresses 30E0_00 to the ID 607
	file.write("m s 0x607 8 0x23 0xE0 0x30 0x00 0x" + lowerByte + " 0x" + upperByte + " 0x00 0x00\n")
	file.close()

	print "\n\nSending following commands via CAN"
	os.system("cat move_sevcon.txt")
	#time.sleep(10)
	print "\n\n"
	###Call the Transmit test program and wait for a max of 3 seconds###

	os.system("./transmitest move_sevcon.txt -f=/dev/pcan32 -b=0x031C -r=500")

	time.sleep(1)




#print "Exiting..."



